### ISSUE TITLE
Delete Single Shopcart Items

### ISSUE THREAD

**Issue by xp2083** [CSCI-GA-2820-SP24-003/shopcarts#10]
**As a** [customer]
**I need** [remove a single item]  
**So that** [I can manage which product to buy]  
   
 ### Details and Assumptions
 * [TBD]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [shopcart is not empty]
 When [removing an item]
 Then [a single item will be removed from the shopcart]
```

**Comment by cisc0f** [comment]
Changed from single/multiple delete to single since we need another endpoint to delete in batch
