### ISSUE TITLE
List Shopcart

### ISSUE THREAD

**Issue by cisc0f** [CSCI-GA-2820-SP24-003/shopcarts#3]
**As a** Shopcart Manager
**I need** to list all the shopcarts
**So that** I can analyze all the products added
   
 ### Details and Assumptions
 * All the shopcarts should have at list one item
 * The endpoint route should be /shopcarts (Method: GET)
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given the manager is authenticated as admin
 When the endpoint is invoked
 Then all shopcarts are returned
```

**Comment by JarryFall** [comment]
LGTM :)
